---
- name: Download configuration files from Bitbucket
  hosts: all
  gather_facts: no
  become: yes
  vars:
    env: dev
    project: ng2
    tier: app
    version: "1.2.1"
    git_location : "/opt/{{ project }}-{{ tier }}-{{ env }}-{{ version }}"
    destination: "/app/opt/deployment/config/"

  tasks:

     - name: Clearing old repository files if any..
#       command: cp -r "{{ git_location }}/{{ env }}/ncp_{{ tier }}/" "{{ destination }}"
       copy:
         src: "{{ git_location }}"
         dest: "{{ destination }}"
         remote_src: no
#         mode: "preserve"
#         remote_src: yes
