---
- name: Ansible test
  hosts: localhost
  tasks:
    - name: launching AWS instance using Ansible
      ec2:
        key_name: aws-tower3.3
        instance_type: t2.micro
        image: ami-0a74bfeb190bd404f
        region: ap-south-1
        wait: yes
        group: sthakre-group
        count: 1
        vpc_subnet_id: subnet-f58e6f9c
        assign_public_ip: yes
