---
- hosts: localhost
  gather_facts: no
  become: yes
  tasks: 
    - name : test
      git:
       repo: 'https://github.com/Saurabh-Thakre/mygit.git'
       dest: /tmp/touch/sam
       delegate_to: localhost
