---
- hosts: all
  gather_facts: no
  become: yes
  tasks: 
    - name: Setup | private key upload
      unarchive: 
       src: "https://repo.continuum.io/archive/.winzip/Anaconda2-2019.07-Windows-x86.zip"
       dest: "/test"
       remote_src: yes
