---
- hosts: all
  gather_facts: no
  become: yes
  tasks: 
    - name : test
      file:
        path: /test/saurabh.conf
        state: touch
        mode: u+rw,g-wx,o-rwx
        deligate_to: localhost
