---
- hosts: win
  vars:
    ansible_user: Administrator
    ansible_password: Cool96sau@
    ansible_connection: winrm
    ansible_port: 5986
    ansible_winrm_server_cert_validation: ignore
  tasks:
    - win_ping:

