---
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    tower_api_url: "https://13.235.42.148"
    tower_token: "wEuCjxA3TQ63iwFtxqQ8tshMkxGFEb"
  tasks:
    - name: Check that tower job has finished
      uri:
        url: "{{ tower_api_url }}/api/v2/jobs/{{ my_tower_job_id }}/"
        method: GET
        validate_certs: no
        status_code: 201, 200
        headers:
          Content-Type: application/json
          Authorization: "Bearer {{ tower_token }}"
      register: job_result
      ignore_errors: true

    - name: show job details for {{ job_id }}
      debug:
        msg: "json.host_status_counts {{ job_result.json.host_status_counts }}"
    
