---
- name: tower_job_list module
  hosts: all
  collections:
    - ansible.tower
  tasks:
    - name: Export all inventories
      tower_export:
        job_template: "Ping"
        credential: 'all'
